#!/usr/bin/env python3
"""Generate stable wire opcodes for Vulkan commands from vk.xml.

Both ends of a remoting link must agree on what number means which command.
Hand-maintaining that list would rot the moment a header updates, so it is
derived from the registry the same way generate_device_dispatch.py derives its
thunks.

Opcodes are assigned by sorted command name rather than registry order, so
adding a command to vk.xml renumbers only what sorts after it, and two peers
built from the same header version always agree. The wire is still
version-sensitive: client and server must be generated from the same vk.xml.
That is checked at connect time by comparing the digest emitted here.
"""

import argparse
import hashlib
import xml.etree.ElementTree as ET


def collect_commands(registry_xml):
    tree = ET.parse(registry_xml)
    root = tree.getroot()

    names = []
    for command in root.findall('commands/command'):
        # Aliases carry no proto of their own; they are resolved by the name
        # they point at, which is already in the list.
        if 'alias' in command.attrib:
            continue
        name = command.find('proto/name')
        if name is None or name.text is None:
            continue
        apis = command.attrib.get('api', 'vulkan').split(',')
        if 'vulkan' not in apis:
            continue
        names.append(name.text)

    return sorted(set(names))


def generate(registry_xml, output):
    names = sorted(collect_commands(registry_xml))

    # Opcodes this protocol adds on top of the Vulkan command set. They exist
    # because mapped memory has no Vulkan call of its own: the application
    # writes through a pointer, and those bytes have to be moved explicitly.
    # They are part of what the two peers must agree on, so they go into the
    # digest as well.
    extras = ['FlushMappedMemory', 'DownloadMappedMemory']

    digest = hashlib.sha256('\n'.join(extras + names).encode('utf-8')).hexdigest()[:16]

    print('// Generated by generate_remoting.py. Do not edit.', file=output)
    print('#pragma once', file=output)
    print('', file=output)
    print('#include <cstdint>', file=output)
    print('', file=output)
    print('namespace remoting {', file=output)
    print('', file=output)
    print('// Identifies the command set both peers were generated from.', file=output)
    print('inline constexpr const char* kCommandSetDigest = "{}";'.format(digest), file=output)
    print('', file=output)
    print('enum class Opcode : uint32_t {', file=output)
    # 0 is reserved so a zeroed or truncated header cannot look like a valid
    # command, and the handshake gets a fixed opcode independent of vk.xml.
    print('    Invalid = 0,', file=output)
    print('    Handshake = 1,', file=output)
    for index, name in enumerate(extras):
        print('    {} = {},'.format(name, index + 2), file=output)
    for index, name in enumerate(names):
        print('    {} = {},'.format(name, index + 2 + len(extras)), file=output)
    print('    Count,', file=output)
    print('};', file=output)
    print('', file=output)
    print('inline const char* opcode_name(Opcode opcode) {', file=output)
    print('    switch (opcode) {', file=output)
    print('        case Opcode::Invalid: return "Invalid";', file=output)
    print('        case Opcode::Handshake: return "Handshake";', file=output)
    for name in extras:
        print('        case Opcode::{}: return "{}";'.format(name, name), file=output)
    for name in names:
        print('        case Opcode::{}: return "{}";'.format(name, name), file=output)
    print('        default: return "Unknown";', file=output)
    print('    }', file=output)
    print('}', file=output)
    print('', file=output)
    print('}  // namespace remoting', file=output)

    return len(names), digest


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('registry_xml', type=str)
    parser.add_argument('--output', type=str, required=True)
    args = parser.parse_args()

    with open(args.output, 'w') as output:
        count, digest = generate(args.registry_xml, output)

    print('generate_remoting.py: {} commands, digest {}'.format(count, digest))
